version: "3"
services:
  backend:
    build: ./backend
    restart: always
    container_name: backend
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - 2000:2000

  frontend:
    restart: on-failure
    build: ./frontend
    container_name: frontend
    command: npm run dev -- --host
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: KEAPlan
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

volumes:
  pgdata:
