name: e2e tests
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd frontend/ && npm install
      - run: docker-compose up --build -d
      - run: cd frontend/src/e2e/ && node interface_tests.cjs
