name: Lint frontend
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd frontend/ && npm install
      - run: cd frontend/ && npm run lint
      - run: cd frontend/ && npm run check
